### ISSUE TITLE
Question about probTran

### ISSUE THREAD

**Issue by nurgasemetey** [melmasri/traveltimeHMM#2]
Hello,

Thank you for this package. As I understand, you want to implement algorithm mentioned in the paper of Woodard. I am reading the paper and can't find `probTran` in the paper? Could you point me if there is some misunderstanding?
https://github.com/melmasri/traveltimeHMM/blob/e79f1d390c758fdfc53190391d3e573c3ac91196/R/traveltimeHMM.R#L168

**Comment by melmasri** [comment]
Added description on the line, see 

https://github.com/melmasri/traveltimeHMM/blob/dd215b576382331a4a9985ca72f69c2cfeb03a39/R/traveltimeHMM.R#L290
