### ISSUE TITLE
Transition matrix dimension

### ISSUE THREAD

**Issue by nurgasemetey** [melmasri/traveltimeHMM#22]
https://github.com/melmasri/traveltimeHMM/blob/dd215b576382331a4a9985ca72f69c2cfeb03a39/R/traveltimeHMM.R#L258

Hello,

When I was reading your code, I noticed that transition matrix is not square? Why is it so?

**Comment by melmasri** [comment]
Each row is a transition matrix. `nQ2` is the square of the number of states `nQ`. Therefore, each row is for a time bin and a link, and the columns are the transition probability. I do this for vectorization.

**Comment by nurgasemetey** [comment]
Sorry, in paper I read following part  

![image](https://user-images.githubusercontent.com/4669437/68129548-cd532b80-ff2a-11e9-877b-ba27e121c019.png)

As you can see it says `transition matrix for the congestion state on link j conditional on the congestion state in the previous link of the trip, during time bin b`. I just can't connect the dots

**Comment by melmasri** [comment]
If you notice `\Gamma` is indexed by `R_{i,k}` and not `{i,k}` only.  `R_{i,k}` is a specific road in the map. Hence for each specific road, for each time bin `(R_{i,k}, b_{i,k})` you get a transition matrix. When `Q=2` the transition matrix is `2x2`, hence the row format would have 4 cells.
